#ifndef ErrorCode_H
#define ErrorCode_H

typedef enum
{			
	ERR_NO_ERROR,
	ERR_EMPTY_STRING,
	ERR_INCOMPLETE_NUMBER, 
	ERR_NOT_NUMBER_TOKEN,
	ERR_NOT_PREFIX_OPERATOR,
	ERR_STACK_EMPTY,
	ERR_STACK_FULL,
	ERR_IDENTIFIER_NOT_SUPPORT,
	ERR_EXPECTING_NUMBER,
	ERR_UNKNOWN_OPERATOR
} Token_ErrorCode;

#endif //ErrorCode_H