#ifndef ErrorCode_H
#define ErrorCode_H

#include <stdio.h>
#include "CException.h"

typedef enum
{
  TLV_NULL_SESSION = 1,
  TLV_TIME_OUT,
  TLV_CORRUPTED_DATA,
  TLV_INVALID_COMMAND,
  TLV_TRANSMISSION_BUSY,
  TLV_CHECKSUM_ERROR,
  TLV_NOT_HALTED,
  TLV_NOT_RUNNING,
  TLV_NOT_STEPPED,
  TLV_NOT_STEPOVER,
  TLV_NOT_STEPOUT,
  TLV_BKPT_NOTHIT,
  TLV_BKPT_MAXSET,
  TLV_ADDRESS_NOT_FOUND,
  TLV_WATCHPOINT_NOTHIT, //12
} Tlv_ErrorCode;

typedef enum
{
  PROBE_TLV_CORRUPTED_DATA = 101,
  PROBE_TLV_TIME_OUT,
  PROBE_TLV_INVALID_COMMAND,
  PROBE_TLV_CHECKSUM_ERROR,
  PROBE_NOT_RESPONDING,
} Probe_ErrorCode;

typedef enum
{			
	ERR_NO_ERROR = 20,
	ERR_EMPTY_STRING,
	ERR_INCOMPLETE_NUMBER, 
	ERR_NOT_NUMBER_TOKEN,
	ERR_NOT_PREFIX_OPERATOR,
	ERR_STACK_EMPTY,
	ERR_STACK_FULL,
	ERR_IDENTIFIER_NOT_SUPPORT,
	ERR_EXPECTING_NUMBER,
	ERR_UNKNOWN_OPERATOR //29
} Token_ErrorCode;

typedef enum{
	ERR_FILE_NOT_EXIST = 31,
	ERR_BYTE_SELECTION,
  ERR_RANGE_OFFSET, //33
} Elf_ErrorCode;

typedef enum
{			
	ERR_INCOMPLETE_COMMAND = 34,
	ERR_INVALID_USER_COMMAND,
	ERR_INVALID_REGISTER_ADDRESS,
  ERR_EXPECT_NUMBER,
  ERR_EXPECT_REGISTER_ADDRESS,
  ERR_EXPECT_FILE_PATH,
  ERR_EXPECT_MEMORY_SELECTION,
  ERR_INVALID_MEMORY_SELECTION,
  ERR_EXPECT_ERASE_SECTION,
  ERR_INVALID_BANK_SELECTION,
  ERR_OPTION_NOT_FOUND,
  ERR_INVALID_COMMAND, //45
} Interface_ErrorCode;

typedef enum
{
  ERR_INVALID_HANDLER = 46,
  ERR_SET_COMM_STATE,
  ERR_SET_COMM_TIMEOUTS,
  ERR_NO_COM_PORT,
  ERR_GET_COMM_STATE,
  ERR_INVALID_PASSKEY, //51
} Handler_ErrorCode;

void displayErrorMessage(CEXCEPTION_T err);
#endif // ErrorCode_H
